[package]
name = "sourcepak"
version = "0.1.0"
edition = "2021"
exclude = [".vscode", ".github", "test_files"]

[features]
respawn = ["revpk", "rpak"]
revpk = ["dep:lzham-alpha-sys"]
rpak = []

[dependencies]
crc = "3.0.1"
lzham-alpha-sys = { version = "0.1.0", optional = true }
